{% set name = "mplt" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b0ec4fc5727438a0730fcd2a7bef001333b09b0d9b89ca560d1bdd0d87870e8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - python

about:
  home: http://github.com/stringhamc/mplt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Set of niceties wrapping matplotlib for signal processing

extra:
  recipe-maintainers:
    - jordan-heemskerk
    - stringhamc
