{% set name = "mplt" %}
{% set version = "2.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 88513d1a7a1e96862c77e7ba9638061f274861cdcd33c1dd5d608a88d50dcebd

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib
    - numpy
    - python

about:
  home: "http://github.com/stringhamc/mplt"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Set of niceties wrapping matplotlib for signal processing"

extra:
  recipe-maintainers:
    - jordan-heemskerk
    - stringhamc
