travis:
  secure:
    BINSTAR_TOKEN: q7eqDb2UcHi9DtUnrkliZsAdTLKz4etdagOlcDvcCBBr2BYMIhrsgIB+qcFNkU0ydEunh1uyieDrMRQuqKvkZ51ZmCeJpA0YlSqEohFWkgfNfsmiJ3vsY1bpZ2JrQuQAGOgCN6qw6TlV11dsvvYtJAXL5/V/n3yfUvM0P0AMo129MIZDwFXJR40Kt4vgmCMbsBP0PvxSuURcE8GdxKqoc/HA8ualUb0wc0aLWyb7xIf0n4RDfygtbWOt0qWM/taO2B/TyBc5g+wOzh0EARsKQBXvZ+92SyW5veyykSM1aGlBya9Hs32JK2sHqOhrPa/BaDuco7nE3oNuqmroNNaFLASd76oFfiDntdos7FxQnsJ9RbBn+rtENN191FL7Zp7eg+SfUK4Nbd9PjTvTv+9xqBGp/3Kkifk1XFGtSC5u12CxqoyKyjC4TjAiPCsPoc3g9AYk2IJflcfzjC3Lwo7Ngm44sq+L/rCtZpGUJtsuNBQc9Gu0n6D22b36HUWhaoTANDs6TrsBmNo4Soxf1u3oXg4zmkV6rlER7Cb06wa3YeXTrkrAzXhHiE+EUWGC1hF3CEXnfSfKzQy/eZjZR5lKbEqls4f4le5ICf1iF6K14O6hhiDWB3zgb/v5BhovCflvvnsT/Qx1nm0s7tSHZ5M8jymYJ6T1pL7Q7E3oNhBFjOo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
